### ISSUE TITLE
Code-formatter ruby error

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/github-actions#130]
Hi there we are running the code-formatter in `ministryofjustice/bichard7-next-infrastructure-modules`, here is our workflow:

```
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ministryofjustice/github-actions/code-formatter@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

We are currently seeing this error:

```
Run ministryofjustice/github-actions/code-formatter@main
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name d61846bb6d8324afb942873d6d6719cbe_2ebf96 --label 08450d --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/bichard7-next-infrastructure-modules/bichard7-next-infrastructure-modules":"/github/workspace" 08450d:61846bb6d8324afb942873d6d6719cbe
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Running: pwd
/github/workspace
Running: terraform fmt -recursive

Running: pwd
/github/workspace
Running: terraform fmt -recursive

Running: pwd
/github/workspace
Running: terraform fmt -recursive

Running: git status --porcelain=1 --untracked-files=no
/github.rb:74:in `modified_files': undefined method `split' for nil:NilClass (NoMethodError)

      .split("\\n")
      ^^^^^^
	from /github.rb:39:in `commit_changes'
	from /code_formatter.rb:12:in `run'
	from /format-code.rb:9:in `<main>'
```
