### ISSUE TITLE
Code formatter causes errors on YAML files encrypted with git-crypt

### ISSUE THREAD

**Issue by mtac50** [ministryofjustice/github-actions#151]
Since [this](https://github.com/ministryofjustice/github-actions/pull/141/files) PR was merged there is now an issue running the code formatter when git-crypt is in use.

In our case we have a docker-compose.yml file which is encrypted using git-crypt and when the formatter is run as part of a PR it is run on the encrypted version of the file and tries to add a new line to the end of the file. When this is merged the file is seen by git-crypt as being "tampered" with.

Would it be possible to update the action so that users can specify a list of files are excluded from the formatting process?

**Comment by NickWalt01** [comment]
Hi can you provide a link to issue please? Is it a specific file name or type as can add a filter for it in the script

**Comment by NickWalt01** [comment]
I'll have a look at how to add a exclude list to GH action via a repo CI .yml file

**Comment by mtac50** [comment]
Hi @NickWalt01, thanks for looking into this. Currently there isn't an issue to link (other than a bug on our Jira board) but I can provide any additional information required. For us the issue is with our YAML files (`docker-compose.override.yml`) however this issue would in theory be experienced by any file type that the code formatter covers if it is encrypted.

**Comment by NickWalt01** [comment]
Hi @mtac50 do you want to try the ignore-file option? Just add the code below to the code-formatter yaml and let me know how it goes?

```
      - uses: ministryofjustice/github-actions/code-formatter@main
        with:
          ignore-files: "fileA.json,fileB.rb,fileC.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
